from typing import Any, Awaitable, Callable, ParamSpec, TypeVar

_P = ParamSpec("_P")
_T = TypeVar("_T")
Injected: Any

def injectable(func: Callable[_P, Awaitable[_T]]) -> Callable[_P, Awaitable[_T]]: ...
def injectable_sync(func: Callable[_P, _T]) -> Callable[_P, _T]: ...
def add_injectable(name: str, injectable: Any) -> None: ...
def add_lazy_injectable(name: str, injectable: Callable[[], Any]) -> None: ...
